name: Deploy Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Initializing process"
      - name: Finalizing process
        run: echo "Process finalized successfuly"
