name: Run Tests
on: workflow_dispatch
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Download infrastructure
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: download nodejs
        run: npm i
        
      - name: run tests
        run: npm run test
