name: Run tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Aqui
        run: echo "haha"
        
  run-something:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: haha
        run: echo "asodjsn"
