name: Run-tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup nodeJS
        uses: actions/setup-node@v3
        
      - name: Download dependencies
        run: npm i
        
      - name: Run tests
        run: npm run test
  
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Build Project
        run: npm run build
        
        
